#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Osuke Ishihara
# SPDX-License-Identifier: BSD-3-Clause

import sys

a = 1
for n in sys.stdin:
    try:
        a *= int(n)
    except:
        a *= float(n)

print(a)
