#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Osuke Ishihara
# SPDX-License-Identifier: BSD-3-Clause

import sys

c = 1
for n in sys.stdin:
    try:
        c *= int(n)
    except:
        c *= float(n)

print(c)
