#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Osuke Ishihara
# SPDX-License-Identifier: BSD-3-Clause

import sys

x = 0
for n in sys.stdin:
    try:
        x += int(n)
    except:   
        x += float(n)

print(x)
