#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Osuke Ishihara
# SPDX-License-Identifier: BSD-3-Clause

import sys

a = b = 0
c = d = 1
for n in sys.stdin:
    try:
        a += int(n)
        b -= int(n)
        c *= int(n)
        d %= int(n)
    except:   
        a += float(n)
        b -= float(n)
        c *= float(n)
        d %= float(n)

print(a)
print(b)
print(c)
print(d)
