#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Osuke Ishihara
# SPDX-License-Identifier: BSD-3-Clause

import sys

b = 0
for n in sys.stdin:
    try:
        b -= int(n)
    except:
        b -= float(n)

print(b)
